name: Generate Documentation
on: push
jobs:
  generate-documentation:
    runs-on: windows-latest
    steps:
      - name: Configure
        run: git config --global core.autocrlf false
      - name: Setup (PHP)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpdoc
      - name: Setup (Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout (Calliope)
        uses: actions/checkout@v4
        with:
          repository: DaphneWebFramework/Calliope
          path: .tmp/Calliope
      - name: Checkout (Documentation)
        uses: actions/checkout@v4
        with:
          repository: DaphneWebFramework/Documentation
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          path: .tmp/Documentation
      - name: Reset
        shell: cmd
        run: RMDIR /S /Q ".tmp/Documentation/${{github.event.repository.name}}" >NUL 2>&1
      - name: Generate (Documentation)
        shell: cmd
        run: |
          phpdoc ^
          --template ".tmp/Calliope" ^
          --target ".tmp/Documentation" ^
          --visibility="public" ^
          --ignore ".git" ^
          --ignore ".github"
      - name: Generate (Index)
        shell: cmd
        run: python ".github/scripts/generateDocumentationIndex.py" ".tmp/Documentation/${{github.event.repository.name}}"
      - name: Publish
        run: |
          cd .tmp/Documentation
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated update from ${{github.event.repository.name}}"
          git push https://DaphneWebFramework:${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/DaphneWebFramework/Documentation.git
      - name: Cleanup
        shell: cmd
        run: RMDIR /S /Q ".tmp"
